spring.application.name=${APP_NAME:User-Service}

# Server configuration
server.port=${SERVER_PORT:9105}

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/home_energy_tracker
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Flyway configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
# This property tells Flyway to automatically baseline an existing database on the first migration.
# This is useful when you have an existing database that you want to start managing with Flyway without having to manually create a baseline version.
# True : Existing database will be baseline on the first migration.
# False: completely Fresh database will be created on the first migration.

#spring.flyway.baseline-on-migrate=false
#spring.flyway.baseline-version=1

# If you are in a heavy development phase and don't mind losing data when you change scripts.
#spring.flyway.clean-disabled=false

spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1

